apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deploy.wafflehacks.cloud
spec:
  secretName: deploy-wafflehacks-cloud-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: deploy.wafflehacks.cloud
  dnsNames:
    - deploy.wafflehacks.cloud
