---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://deploy.wafflehacks.cloud

  subscriptions: |
    - recipients:
        - github
      triggers:
        - sync-state-change

  trigger.sync-state-change: |
    - when: app.status.operationState.phase in ['Running']
      send: [github-commit-status, app-sync-running]
    - when: app.status.operationState.phase in ['Succeeded']
      send: [github-commit-status, app-sync-succeeded]
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [github-commit-status, app-sync-failed]

  template.github-commit-status: |
    message: |
      {{.app.spec.project}}/{{.app.metadata.name}} is {{.app.status.operationState.phase}}.
    github:
      status:
        state: >-
          {{- if eq .app.status.operationState.phase "Running" -}}
            pending
          {{- else if eq .app.status.operationState.phase "Succeeded" -}}
            success
          {{- else if eq .app.status.operationState.phase "Error" -}}
            error
          {{- else if eq .app.status.operationState.phase "Failed" -}}
            error
          {{- end -}}
        label: "argocd/{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"

  service.github: |
    appID: 127650
    installationID: 18414310
    privateKey: $github-privateKey
