---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"
  statusbadge.enabled: "true"
  url: https://deploy.wafflehacks.cloud

  server.log.level: debug

  policy.default: role:readonly
  policy.csv: |
    g, WaffleHacks:technology, role:readonly
    g, WaffleHacks:deployments, role:admin

  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: c1bfab9c9cbda442050c
          clientSecret: $dex.github.clientSecret
          orgs:
            - name: WaffleHacks
              teams:
                - deployments
                - technology
          loadAllGroups: true
          teamNameField: slug
