---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"
  statusbadge.enabled: "true"
  url: https://deploy.wafflehacks.cloud

  application.links: |
    - url: {{.metadata.annotations.publicURL}}
      title: URL
      icon: globe
      if: metadata.annotations.publicURL

  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: c1bfab9c9cbda442050c
          clientSecret: $dex.github.clientSecret
          orgs:
            - name: WaffleHacks
              teams:
                - deployments
                - technology
          loadAllGroups: true
          teamNameField: slug
