apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    g, WaffleHacks:technology, role:readonly
    g, WaffleHacks:deployments, role:admin
