apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    vault:
      server: https://vault.wafflehacks.cloud
      path: services
      version: v2

      auth:
        appRole:
          path: approle
          roleId: 6974029a-6f65-9ad1-afb0-cdef5fb4b9f5
          secretRef:
            namespace: external-secrets
            name: vault-credentials
            key: secretId
