---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: data.wafflehacks.org
spec:
  secretName: data-wafflehacks-org-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: data.wafflehacks.org
  dnsNames:
    - data.wafflehacks.org
