---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:v0.45.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MB_JETTY_HOST
              value: "0.0.0.0"
            - name: MB_JETTY_PORT
              value: "3000"
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: metabase-database-password
                  key: databaseUrl
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-database
                  key: PGUSER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-database
                  key: PGPASSWORD
            - name: JAVA_TIMEZONE
              value: "America/New_York"
            - name: MB_EMOJI_IN_LOGS
              value: "false"
            - name: MB_COLORIZE_LOGS
              value: "false"
            - name: MB_ADMIN_EMAIL
              value: technology@wafflehacks.org
            - name: MB_SITE_NAME
              value: "WaffleHacks Data"
            - name: MB_SITE_URL
              value: "https://data.wafflehacks.org"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
