---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: data.wafflehacks.org
spec:
  virtualhost:
    fqdn: data.wafflehacks.org
    tls:
      secretName: data-wafflehacks-org-tls
  routes:
    - services:
        - name: metabase
          port: 80
