---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: projectcontour
    server: https://storage-zlfhku:6443
  project: default
  source:
    path: contour
    repoURL: https://github.com/WaffleHacks/infrastructure-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
