---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metabase
    server: https://kubernetes.default.svc
  project: wafflehacks
  source:
    path: metabase
    repoURL: https://github.com/WaffleHacks/infrastructure-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
