---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: secret-store
    repoURL: https://github.com/WaffleHacks/infrastructure-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
