---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: newrelic

resources:
  - base/namespace.yaml
  - base/secret.yaml

helmCharts:
  - name: nri-bundle
    repo: https://helm-charts.newrelic.com
    version: 5.0.4
    releaseName: nri-bundle
    valuesFile: values.yaml
