---
on:  # yamllint disable-line rule:truthy
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install yamllint
      - run: yamllint -s -f github .
